version: '3'
services:
  myerp.db:
    image: postgres:9.5
    ports:
      - "32770:5432"
    # volumes:
# #       - ./docker-entrypoint-initdb.d:/var/lib/postgresql/data
       # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=db_myerp
      - POSTGRES_USER=usr_myerp
      - POSTGRES_PASSWORD=myerp

